# Generated by Django 5.0.7 on 2024-12-06 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='owner',
            new_name='relates_to',
        ),
    ]
