# Generated by Django 5.0.7 on 2024-12-06 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_rename_owner_task_relates_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='relates_to',
            new_name='owner',
        ),
    ]
