# Generated by Django 5.0.7 on 2024-12-12 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
